- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Add Iosevka Font to COPR
      become: true
      community.general.copr:
        name: peterwu/iosevka

    - name: Install Packages
      become: true
      ansible.builtin.dnf:
        name:
          - neovim
          - python3-neovim
          - emacs
          - iosevka-fixed-ss05-fonts
          - kitty
        state: present

    - name: Symlink emacs
      ansible.builtin.file:
        src: ~/dotfiles/config/emacs
        dest: ~/.emacs.d
        state: link

    - name: Create config dir for kittyterm
      ansible.builtin.file:
        path: ~/.config/kitty
        state: directory

    - name: Symlink kittyterm config
      ansible.builtin.file:
        src: ~/dotfiles/config/kitty.conf
        dest: ~/.config/kitty/kitty.conf
        state: link